### ISSUE TITLE
pre-hook treats any new files as Secrets

### ISSUE THREAD

**Issue by chrede88** [red-lichtie/sops-pre-commit-hook#1]
I'm having an issue with the hook, where any new file that's committed is treated as a secret and the hook fails (exit code 1).

This is my `.sops.yaml` config file:
```yaml
creation_rules:
  - path_regex: cluster/talos/config/talsecret(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(cluster|secrets|trustdinfo|certs)$
    age: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
  - path_regex: cluster/talos/.*.ya?ml # Talos config
    input_type: yaml
    encrypted_regex: ^(token|crt|key|id|secret|secrets|secretboxEncryptionSecret|ca)$
    age: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
  - path_regex: cluster/kubernetes/.*.ya?ml # Kubernetes secrets
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    age: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4

stores:
  yaml:
    indent: 2
```
The relevant `path_regex` is the last one (haven't tried others paths).

I've a bunch a new files (just dumping a couple here for brevity) which clearly aren't secrets.
`cluster/kubernetes/flux/resources/helm/dragonfly.yaml`
`cluster/kubernetes/apps/database/kustomization.yaml` 

But they seem to be picked up as `kind: Secret` by the hook somehow. Actually, I'm not committing any `kind: Secret` files.

The output when trying to commit is:
```
Ensure required files are encrypted with CNCF sops.......................Failed
- hook id: sops-pre-commit-hook
- exit code: 1

NOT encrypted: cluster/kubernetes/flux/resources/helm/dragonfly.yaml
NOT encrypted: cluster/kubernetes/apps/database/kustomization.yaml
```

I'm running `v1.1.1` of the hook.

**Comment by chrede88** [comment]
Same happened with some existing files. At this point I think It just thinks all files are `kind: Secret`. Maybe I'm missing something in my setup?

**Comment by red-lichtie** [comment]
Hi, I think that your regex is matching anything under `cluster/kubernetes/` that ends in `ya?ml`.

You have a wild card for everything `.*.` before the `y`.

Also, the hook only matches the `path_regex`, not the `encrypted_regex`.

**Comment by red-lichtie** [comment]
Maybe you could try a path like this `cluster/kubernetes/.*\.sops\.ya?ml` so sops files always end in `.sops.yaml` or `.sops.yml` ?

**Comment by chrede88** [comment]
I see, so your hook is relying on specific secret names? onedr0p's old hook somehow worked fine with my setup.

here for reference: https://github.com/onedr0p/sops-pre-commit

**Comment by chrede88** [comment]
I see. Your hook only checks if it's actually a secret if it can't find a sops config.
https://github.com/red-lichtie/sops-pre-commit-hook/blob/main/hooks/sops_pre_commit_hook.py#L95

**Comment by red-lichtie** [comment]
The pre-commit-hook from onedr0p only works with kubernetes secrets. If it doesn't contain `"^kind:\ssecret$"` then it is ignored. My one allows for other file types but relies on the file being identifiable.

For example I have both `.*\.prod\.ya?ml`  and `.*\.test\.ya?ml`  which also allows for different keys for different target clusters.

**Comment by chrede88** [comment]
Okay! Thanks for clarifying.

**Comment by red-lichtie** [comment]
For reference, here is my configuration. All the secrets are encrypted with at least my key (so I can edit them) and by a cluster key.
```yaml
---
creation_rules:
  - path_regex: .*\.prod\.ya?ml
    encrypted_regex: ^(data|stringData|key|api-token|token|secretboxEncryptionSecret|secret)$
    # Personal, Flux-Prod
    age: >-
      age1wgq6wt4yfnqg8nw7nrd27sc90xllpxwgd9vgj653cns8cmn7230syhkq95,
      age1jtm9h6g5r9a5rasy6nuaa72zwfx2vfn2wmm6302ju8tsl3l45p4qta2d32
  - path_regex: .*\.test\.ya?ml
    encrypted_regex: ^(data|stringData|key|api-token|token|secretboxEncryptionSecret|secret)$
    # Personal + Flux-Test
    age: >-
      age1wgq6wt4yfnqg8nw7nrd27sc90xllpxwgd9vgj653cns8cmn7230syhkq95,
      age1tz5je5dz9z85sfnhr6hff0n70z629aq5n8jm89gk7yqjggsc5qkswhdca8
  - path_regex: (kubeconfig|talosconfig|credentails\.auto\.tfvars)
    # Personal + Flux-Prod
    age: >-
      age1wgq6wt4yfnqg8nw7nrd27sc90xllpxwgd9vgj653cns8cmn7230syhkq95,
      age1jtm9h6g5r9a5rasy6nuaa72zwfx2vfn2wmm6302ju8tsl3l45p4qta2d32
stores:
  yaml:
    indent: 2
...
```
